#ifndef CACHE_LEVEL_THRESHOLDS_H
#define CACHE_LEVEL_THRESHOLDS_H

#include <stdint.h>

#define CACHE_LEVEL_L1_MAX_TICKS UINT64_C(44)
#define CACHE_LEVEL_L2_MAX_TICKS UINT64_C(81)
#define CACHE_LEVEL_LLC_MAX_TICKS UINT64_C(182)

#endif
