#include <stdint.h>

#define CACHE_HIT_THRESHOLD (125)
#define NOT_MISPREDICTION_DELAY_STEPS (28)
#define NAND_MISPREDICTION_DELAY_STEPS (50)
#define NAND2_MISPREDICTION_DELAY_STEPS (27)

extern int64_t SLOW_PARAM;
